import pyaudio

FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 192000
MAVLINK_SERIAL_PORT = 'COM11'
MAVLINK_SERIAL_BAUDRATE = 57600
PACKETS_TO_COLLECT_WITHOUT_AUDIO = 200
PACKETS_TO_COLLECT_WITH_AUDIO = 50
USE_SAMPLE_PACKETS = False
RESET_INPUT_BUFFER = False
PACKET_TYPE_TO_ANALYZE = 'RAW_IMU'  # MAVLINK_MSG_ID_HIGHRES_IMU
PACKET_TYPE_UPDATE_RATE_TO_REQUEST = 5
INITIAL_AUDIO_FREQUENCY = 1700
AUDIO_FREQUENCY_LIMIT = 2000
AUDIO_FREQUENCY_STEP = 50

SAMPLE_DATA_PATH = 'sample_data'
