import pyaudio

from enums import PacketType

AUDIO_FORMAT = pyaudio.paInt32
AUDIO_CHANNELS = 2
AUDIO_SAMPLING_RATE = 192000

MAVLINK_SERIAL_PORT = "COM11"
MAVLINK_SERIAL_BAUDRATE = 57600

PACKETS_TO_COLLECT_WITHOUT_AUDIO = 200
PACKETS_TO_COLLECT_WITH_AUDIO = 50
MOCK_DRONE_CONTROLLER = True
RESET_INPUT_BUFFER = False
PACKET_TYPE_TO_ANALYZE = PacketType.RAW_IMU
PACKET_TYPE_UPDATE_RATE_TO_REQUEST = 5
INITIAL_AUDIO_FREQUENCY = 24100
AUDIO_FREQUENCY_LIMIT = 25000
AUDIO_FREQUENCY_STEP = 100
SHOW_PLOTS = False

FREQUENCY_COL_NAME = "Frequency"

LOGS_FOLDER = "logs"
MOCK_DATA_FOLDER = "mock_data"
COLLECTED_DATA_FOLDER = "collected_data"

LOG_FILE_NAME = "main.log"
